movproject/movapp/urls.py
from . import views
from django.urls import path

app_name='movapp'
urlpatterns = [

    path('',views.main,name='main'),
    path('movie/<int:mov_id>/',views.datail,name='detail'),
    path('add/',views.add_field,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

movproject/movproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movapp.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movproject/movapp/models.py
from django.db import models

# Create your models here.
class Mov(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')


    def __str__(self):
        return self.name

movproject/movapp/forms.py
from django import forms
from .models import Mov


class movform(forms.ModelForm):
    class Meta:
        model = Mov
        fields = ['name', 'desc', 'desc', 'image']

movproject/movapp/views.py
from django.shortcuts import render, redirect
from .models import Mov
from .forms import movform


# Create your views here.
def main(request):
    obj = Mov.objects.all()
    return render(request, 'index.html', {'mov': obj})


def datail(request, mov_id):
    obj = Mov.objects.get(id=mov_id)
    return render(request, 'detail.html', {'movies': obj})


def add_field(request):
    if request.method == 'POST':
        movie = request.POST.get('name')
        desc = request.POST.get('desc')
        yr = request.POST.get('year')
        img = request.FILES['image']
        mov = Mov(name=movie, desc=desc, year=yr, image=img)
        mov.save()

        return redirect('/')
    return render(request,'a_field.html')


def update(request, id):
    model_mov = Mov.objects.get(id=id)
    form_py = movform(request.POST or None, request.FILES, instance=model_mov)
    if form_py.is_valid():
        form_py.save()
        return redirect('/')
    return render(request, 'edit.html', {'formpy': form_py, 'mov_model': model_mov})


def delete(request, id):
    if request.method == 'POST':
        obj = Mov.objects.get(id=id)
        obj.delete()
        return redirect('/')
    return render(request,'delete.html')

movproject/templates/a_field.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="add movie "><br>
    <input type="text" name="desc" placeholder="add description "><br>
    <input type="text" name="year" placeholder="Release year "><br>
    <input type="file" name="image" ><br>
    <input type="submit">

</form>
{% endblock %}

movproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Movie list
  </a>
</nav>
<div class="margin-top">
{% block body %}
{% endblock %}
    </div>
</body>
</html>

movproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  delete ?
  <input type="submit">
</form>

movproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movies.image.url}}" width="350" height="250">
        </div>
        <div class="col-md-6">
            <h2>{{movies.name}}</h2>
            Release year <sup>{{movies.year}}</sup>
            <h6>{{movies.desc}}</h6>

            <a class="btn btn-warning" href="{% url 'movapp:update' movies.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movapp:delete' movies.id %}">Delete</a>
        </div>
    </div>
</div>


{% endblock %}

movproject/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{formpy.as_p}}
    <input type="submit">



</form>

movproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in mov %}
        <div class="col-md-3" style="margin-top:20px">

            <div class="card-deck"  >
                <div class="card" style="width: 18rem; height : 30rem">

                    <img class="card-img-top" src="{{i.image.url}}" width="269" height="180" alt="Card image cap">
                    <div class="card-body" >
                        <h5 class="card-title">{{i.name}}</h5>
                        <p class="card-text">{{i.year}}</p>
                        <a href="{% url 'movapp:detail' i.id %}" class="btn btn-primary">View more</a>
                        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                    </div>


                </div>



            </div>

        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}